import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create new game with fun",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h3>Hello global text</h3>
        </header>
        {children}
        <footer>
          <h3>Hello global footer</h3>
        </footer>
      </body>
    </html>
  );
}
